version: '3.8'

services:
  backend:
    build: ./backend
    container_name: multimodal-search-backend
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5500/app_db
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: multimodal-search-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8005
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: multimodal-search-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5500
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: