version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8005
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5500/app_db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5500"
    ports:
      - "5500:5500"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    command: -p 5500
volumes:
  postgres_data: